#############################################################################
# Makefile for building: RSS
# Generated by qmake (2.01a) (Qt 4.3.4) on: Thu Jun 5 17:18:09 2008
# Project:  RSS.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile RSS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SHARED -DQT_NO_DEBUG -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -fpermissive -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Iinterface -Isimulator -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,--no-undefined
LIBS          = $(SUBLIBS)  -L/usr/X11R6/lib -L/usr/lib -Llib -lQGLViewer -lpthread -lGLU -lGL -lQtXml -lQtOpenGL -lQtGui -lQtCore
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./release

####### Files

SOURCES       = main.cpp \
		interface/cameracontrolswidget.cpp \
		interface/configdialog.cpp \
		interface/consolewidget.cpp \
		interface/controlswidget.cpp \
		interface/globwidget.cpp \
		interface/glwidget.cpp \
		interface/informationsbox.cpp \
		interface/mainwindow.cpp \
		interface/pages.cpp \
		interface/speedcontrolswidget.cpp \
		simulator/GLViewer.cpp moc_cameracontrolswidget.cpp \
		moc_configdialog.cpp \
		moc_consolewidget.cpp \
		moc_controlswidget.cpp \
		moc_globwidget.cpp \
		moc_glwidget.cpp \
		moc_informationsbox.cpp \
		moc_mainwindow.cpp \
		moc_speedcontrolswidget.cpp \
		qrc_application.cpp
OBJECTS       = main.o \
		cameracontrolswidget.o \
		configdialog.o \
		consolewidget.o \
		controlswidget.o \
		globwidget.o \
		glwidget.o \
		informationsbox.o \
		mainwindow.o \
		pages.o \
		speedcontrolswidget.o \
		GLViewer.o \
		moc_cameracontrolswidget.o \
		moc_configdialog.o \
		moc_consolewidget.o \
		moc_controlswidget.o \
		moc_globwidget.o \
		moc_glwidget.o \
		moc_informationsbox.o \
		moc_mainwindow.o \
		moc_speedcontrolswidget.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		RSS.pro
QMAKE_TARGET  = RSS
DESTDIR       = 
TARGET        = RSS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RSS.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile RSS.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile RSS.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RSS1.0.0 || $(MKDIR) .tmp/RSS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RSS1.0.0/ && $(COPY_FILE) --parents interface/cameracontrolswidget.h interface/configdialog.h interface/consolewidget.h interface/controlswidget.h interface/globwidget.h interface/glwidget.h interface/informationsbox.h interface/mainwindow.h interface/pages.h interface/speedcontrolswidget.h simulator/GLViewer.h .tmp/RSS1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/RSS1.0.0/ && $(COPY_FILE) --parents main.cpp interface/cameracontrolswidget.cpp interface/configdialog.cpp interface/consolewidget.cpp interface/controlswidget.cpp interface/globwidget.cpp interface/glwidget.cpp interface/informationsbox.cpp interface/mainwindow.cpp interface/pages.cpp interface/speedcontrolswidget.cpp simulator/GLViewer.cpp .tmp/RSS1.0.0/ && (cd `dirname .tmp/RSS1.0.0` && $(TAR) RSS1.0.0.tar RSS1.0.0 && $(COMPRESS) RSS1.0.0.tar) && $(MOVE) `dirname .tmp/RSS1.0.0`/RSS1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RSS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_cameracontrolswidget.cpp moc_configdialog.cpp moc_consolewidget.cpp moc_controlswidget.cpp moc_globwidget.cpp moc_glwidget.cpp moc_informationsbox.cpp moc_mainwindow.cpp moc_speedcontrolswidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cameracontrolswidget.cpp moc_configdialog.cpp moc_consolewidget.cpp moc_controlswidget.cpp moc_globwidget.cpp moc_glwidget.cpp moc_informationsbox.cpp moc_mainwindow.cpp moc_speedcontrolswidget.cpp
moc_cameracontrolswidget.cpp: interface/cameracontrolswidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/cameracontrolswidget.h -o moc_cameracontrolswidget.cpp

moc_configdialog.cpp: interface/configdialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/configdialog.h -o moc_configdialog.cpp

moc_consolewidget.cpp: interface/consolewidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/consolewidget.h -o moc_consolewidget.cpp

moc_controlswidget.cpp: interface/cameracontrolswidget.h \
		interface/speedcontrolswidget.h \
		interface/controlswidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/controlswidget.h -o moc_controlswidget.cpp

moc_globwidget.cpp: interface/globwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/globwidget.h -o moc_globwidget.cpp

moc_glwidget.cpp: interface/glwidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/glwidget.h -o moc_glwidget.cpp

moc_informationsbox.cpp: interface/informationsbox.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/informationsbox.h -o moc_informationsbox.cpp

moc_mainwindow.cpp: interface/consolewidget.h \
		interface/controlswidget.h \
		interface/cameracontrolswidget.h \
		interface/speedcontrolswidget.h \
		interface/informationsbox.h \
		interface/configdialog.h \
		interface/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/mainwindow.h -o moc_mainwindow.cpp

moc_speedcontrolswidget.cpp: interface/speedcontrolswidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) interface/speedcontrolswidget.h -o moc_speedcontrolswidget.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		images/script_gear.png \
		images/comment.png \
		images/logo.png \
		images/systemsettings.png \
		images/folder_page_white.png \
		images/control_start_blue.png \
		images/monitor.png \
		images/script_save.png \
		images/control_play_blue.png \
		images/x.png \
		images/door_in.png \
		images/control_repeat_blue.png \
		images/script.png \
		images/control_stop_blue.png \
		images/cog.png \
		images/browser.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp interface/mainwindow.h \
		interface/consolewidget.h \
		interface/controlswidget.h \
		interface/cameracontrolswidget.h \
		interface/speedcontrolswidget.h \
		interface/informationsbox.h \
		interface/configdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cameracontrolswidget.o: interface/cameracontrolswidget.cpp interface/cameracontrolswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameracontrolswidget.o interface/cameracontrolswidget.cpp

configdialog.o: interface/configdialog.cpp interface/configdialog.h \
		interface/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configdialog.o interface/configdialog.cpp

consolewidget.o: interface/consolewidget.cpp interface/consolewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o consolewidget.o interface/consolewidget.cpp

controlswidget.o: interface/controlswidget.cpp interface/controlswidget.h \
		interface/cameracontrolswidget.h \
		interface/speedcontrolswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlswidget.o interface/controlswidget.cpp

globwidget.o: interface/globwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globwidget.o interface/globwidget.cpp

glwidget.o: interface/glwidget.cpp interface/glwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o glwidget.o interface/glwidget.cpp

informationsbox.o: interface/informationsbox.cpp interface/informationsbox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o informationsbox.o interface/informationsbox.cpp

mainwindow.o: interface/mainwindow.cpp interface/mainwindow.h \
		interface/consolewidget.h \
		interface/controlswidget.h \
		interface/cameracontrolswidget.h \
		interface/speedcontrolswidget.h \
		interface/informationsbox.h \
		interface/configdialog.h \
		simulator/GLViewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o interface/mainwindow.cpp

pages.o: interface/pages.cpp interface/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pages.o interface/pages.cpp

speedcontrolswidget.o: interface/speedcontrolswidget.cpp interface/speedcontrolswidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speedcontrolswidget.o interface/speedcontrolswidget.cpp

GLViewer.o: simulator/GLViewer.cpp simulator/GLViewer.h 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLViewer.o simulator/GLViewer.cpp

moc_cameracontrolswidget.o: moc_cameracontrolswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cameracontrolswidget.o moc_cameracontrolswidget.cpp

moc_configdialog.o: moc_configdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_configdialog.o moc_configdialog.cpp

moc_consolewidget.o: moc_consolewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_consolewidget.o moc_consolewidget.cpp

moc_controlswidget.o: moc_controlswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_controlswidget.o moc_controlswidget.cpp

moc_globwidget.o: moc_globwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_globwidget.o moc_globwidget.cpp

moc_glwidget.o: moc_glwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_glwidget.o moc_glwidget.cpp

moc_informationsbox.o: moc_informationsbox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_informationsbox.o moc_informationsbox.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_speedcontrolswidget.o: moc_speedcontrolswidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speedcontrolswidget.o moc_speedcontrolswidget.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

